server:
  port: 8084
  context-path: /ctwechat/
spring:
    datasource:
        name: test
        url: jdbc:mysql://10.66.110.255:3306/valet?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true
        username: cdb_outerroot
        password: CHEtong@828
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,log4j
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  config-location: classpath:config/mybatis_config.xml

## 自定义配置
headerUrl: http://cs.chetong.net/

appid: wx7daf851ff9bac648
appsecret: 9072255787f6a773122600fe058582ac
WE_CHAT_PUSH_SWITCH: Y
zookeeper.address: 10.249.145.160:2181
dubbo.group: master
