server:
  port: 8084
  context-path: /ctwechat/
spring:
    datasource:
        name: test
        url: jdbc:mysql://10.66.132.211:3306/valet_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true
        username: root
        password: chetong@828
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,log4j
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  config-location: classpath:config/mybatis_config.xml

## 自定义配置
headerUrl: http://dev.chetong.net/

appid: wx8eda4c135b1ad9f7
appsecret: 7a6d09c0f8a25118f109785d942f09f1
WE_CHAT_PUSH_SWITCH: Y
zookeeper.address: 10.249.145.160:2181
dubbo.group: develop
