server:
  port: 8084
  context-path: /ctwechat/
spring: 
    datasource: 
        name: test
        url: jdbc:mysql://localhost:3306/betadb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true
        username: lijq
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,log4j
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  config-location: classpath:config/mybatis_config.xml

## 自定义配置
headerUrl: http://beta.chetong.net/

appid: wx7daf851ff9bac648
appsecret: 9072255787f6a773122600fe058582ac__________ # 不要影响生产环境的获取access_token
WE_CHAT_PUSH_SWITCH: N
zookeeper.address: 10.104.27.127:2181
dubbo.group: beta

loginValidTime: 3600
redis.host: 10.104.27.127
redis.port: 6379
redis.auth: RZhEuSHinS6kDZ81

# 亿美短信服务器配置
softwareSerialNo: 9999999
key: fgujdasg5559

# tencent短信服务器配置
sdkappid: 1400018407
appkey: 0c65dbcfb327977a2fa54df651652689

# 是否测试环境.
isTestEnv : Y

# 邦业总部的userId
anBangCompanyUserId: 30367

# 微信公众号的消息模板ID,推送模板消息时必须要.
newOrderTemplateId: ldGBS8oX2fMnF6kdfGIGCH-6VgUjitbouccjLi5VDA4
changeStatTemplateId: Jvo5tzKR8X8GnjkRpg-fBsjZJmkIBxYq9O4VZJyMgIc